#!/usr/bin/env bash

# check that a command or function or alias exists
# thus conclude that something is installed
# only missing -x check for the executables, which would depend on type

COMMAND_FN=check-x
check-x() {
  if [ $# -eq 0 ]; then
    echo "Usage: check-x <command>"
    false; return
  elif [ -z "$(command -v $1)" ]; then
    # Empty string of command -v (is good enough)
    # Don't check for ! [ -x ...] because that doesn't catch a function or alias
    echo
    echo "Command '$1' not found."
    false; return
  fi
}

[ $(basename $0) = $COMMAND_FN ] && $COMMAND_FN "$@"
