#!/usr/bin/env bash

COMMAND_FN=check-x
DEPENDS_ON="src/os" # aliases use that

# check that a command exists and is executable
# alias to a command is also good
# a 0 exit status means it's something that can be run,
# therefore considered "installed"

# NOTE: phasing it out, especially with regards to sourced use/**/*.sh scripts
# perormance reasons, also because it basically does [ -x "$(command -v $1)" ]

# TODO: depends on BASH_ALIASES & thus only for bash - change for zsh support
# NOTE: all would be so much easier if aliases not checked -- is that needed?
# ... I think there was a special case because of closh


check-x() {
  if [ $# -eq 0 ]; then
    echo "Usage: check-x <command>"
    false; return
  elif [ -x "$(command -v $1)" ]; then
    # executable
    true; return
  else
    # an alias?
    if [ $(basename $0) == "$COMMAND_FN" ]; then
      # a subshell without aliases...
      shopt -s expand_aliases
      holy-dot use/aliases.sh
    fi
    if alias $1 >/dev/null 2>&1; then
      local CMD=$(echo ${BASH_ALIASES[$1]} | grep -o "^\S*")
      if [ -x "$(command -v $CMD)" ]; then
        # alias of a command that can be executed
        true; return
      fi
    fi
    # command `$1` not found
    false; return
  fi
}

[ -n "$DEPENDS_ON" ] && holy-dot $DEPENDS_ON
[ $(basename $0) == "$COMMAND_FN" ] && $COMMAND_FN "$@"
