#!/usr/bin/env bash

# Depends on ./curl-report (if sourced)

# uses curl-report to download something and make it executable
# at a given filepath as a 1st arg, the rest of args being same as curl-report
# this was started as some downloads fail and thus installs become unpredictable

COMMAND_FN=curl-install
curl-install() {
  if [ $# -lt 2 ]; then
    echo "Usage: $(basename $0) <filepath> <url> [curl-options]"
    false; return
  else
    local FILEPATH=${1}
    local RELOCATE=$(dirname ${FILEPATH})
    local FILENAME=$(basename ${FILEPATH})
    if curl-report ${@:2} --create-dirs -o ~/tmp/${FILENAME}; then
      chmod +x ~/tmp/${FILENAME} && mkdir -p ${RELOCATE}
      if [ ! ~/tmp/${FILENAME} -ef ${FILEPATH} ]; then
        mv ~/tmp/${FILENAME} ${FILEPATH}
      fi
      echo "Located:"
      echo "$(ls -l ${FILEPATH})"
      true; return
    elif [ -f ~/tmp/${FILENAME} ]; then
      rm ~/tmp/${FILENAME}
      false; return
    fi
  fi
}

[ $(basename $0) = $COMMAND_FN ] && $COMMAND_FN "$@" || export -f $COMMAND_FN
