#!/usr/bin/env bash

# Depends on ./curl-install and ./move-to if sourced.

# Install some file from GitHub.

COMMAND_FN=gh-install
gh-install() {
  if [ $# -lt 2 ]; then
    echo "Usage: $(basename $0) user/repo file-path [save-to-dir or ./] [branch or master] [move-to-path]"
    false; return
  fi

  local REPOPATH=$1
  local FILEPATH=$2
  local FILENAME=$(basename ${FILEPATH})
  local SAVE_DIR=${3-$(pwd)}
  local BRANCH=${4-"master"}
  local MOVE_TO=$5 # a filename without a path will rename the file at $SAVE_DIR

  local GET_THIS="https://raw.githubusercontent.com/${REPOPATH}/${BRANCH}/${FILEPATH}"

  curl-install ${SAVE_DIR}/${FILENAME} ${GET_THIS}
  local status=$?

  # if success and a $MOVE_TO arg given
  if [[ $status -eq 0 && ! -z ${5+x} ]]; then
    # move or simply rename the file if given a filename, or a path to it
    local TARGET=$(move-to ${SAVE_DIR}/${FILENAME} $MOVE_TO --target 2>&1)
    status=$?
    [[ status -eq 0 ]] && echo "Finally: $TARGET" || echo $TARGET
  fi

  return $status
}

[ $(basename $0) != $COMMAND_FN ] && export -f $COMMAND_FN || $COMMAND_FN "$@"
