#!/usr/bin/env bash

# Depends on ./curl-install if sourced.

# Install some file from GitHub.

COMMAND_FN=gh-install
gh-install() {
  if [ $# -lt 2 ]; then
    echo "Usage: $(basename $0) user/repo file-path [save-to-dir or ./] [branch or master]"
    false; return
  fi

  local REPOPATH=$1
  local FILEPATH=$2
  local FILENAME=$(basename ${FILEPATH})
  local SAVE_DIR=${3-$(pwd)}
  local BRANCH=${4-"master"}

  local GET_THIS="https://raw.githubusercontent.com/${REPOPATH}/${BRANCH}/${FILEPATH}"

  curl-install ${SAVE_DIR}/${FILENAME} ${GET_THIS}
}

[ $(basename $0) = $COMMAND_FN ] && $COMMAND_FN "$@" || export -f $COMMAND_FN
