#!/usr/bin/env bash

COMMAND_FN=move-to
move-to() {
  if [ $# -lt 2 ]; then
    echo "Usage: move-to from-path to-path [--target]"
    echo
    echo "If the to-path is just a filename then it simply renames."
    echo "If --target is asked for, then move-to does echo where it ends up."
    false; return
  fi

  local ORIGIN="$1"
  local TARGET="$2"
  local TO_DIR=$(dirname "$TARGET")

  if [ ! -f "$ORIGIN" ]; then
    echo "Not Found: $ORIGIN"
    false; return
  fi

  if [[ $TO_DIR == "." && $TO_DIR != "./*" ]]; then
    # dirname not given (just a filename target) and not explicitly current ./
    TO_DIR=$(dirname "$ORIGIN")
    TARGET="$TO_DIR"/"$TARGET"
  elif [[ ! -e "$TARGET" && ! -d "$TO_DIR" ]]; then
    # $TARGET doesn't exist
    # make sure its $TO_DIR exists
    mkdir -p "$TO_DIR"
  fi

  mv "$ORIGIN" "$TARGET"
  local status=$?
  [[ $3 == "--target" && $status -eq 0 ]] && echo "$TARGET"
  return $status
}

[ $(basename $0) != $COMMAND_FN ] && export -f $COMMAND_FN || $COMMAND_FN "$@"
