#!/usr/bin/env bash

COMMAND_FN=on-lines
on-lines() {
  if [ $# -lt 2 ]; then
    >&2 echo "$COMMAND_FN ${1+"'$1'"} ${@:2}"
    >&2 echo "required args:"
    >&2 echo "- \$1 regular expression"
    >&2 echo "- \$2 path to file"
    false; return
  fi
  local lines=$(grep -n "$1" $2)
  if [ -n "$lines" ]; then
    # TODO: make the next line optional based on a flag for more than numbers
    lines=$(echo "$lines" | grep -Eo '^[0-9]*' | awk 'ORS=", "' | head -c -2)
    echo "$lines"
    true
  else
    false
  fi
}

[ $(basename $0) != $COMMAND_FN ] && export -f $COMMAND_FN || $COMMAND_FN "$@"
