#!/usr/bin/env bash

COMMAND_FN=urbito
urbito() {
  if [ $# -eq 0 ]; then
    echo "Usage: $COMMAND_FN <urbito-*> [args]"
    false; return
  elif [ $1 == "install" ]; then
    "$DOTS_HOME/install/urbit"
  else
    cd "$HOME"/data/urbit
    ~/bin/urbito/$1 ${@:2}
  fi
}

[ $(basename $0) != $COMMAND_FN ] && export -f $COMMAND_FN || $COMMAND_FN "$@"
