#!/usr/bin/env bash

HOLY_COPY="Bless the OS"
HOLY_GOAL=HOLY_HOME

# with the above two vars we validate first-time init + set the HOLY_GOAL home
. $(dirname $0)/once.sh


tee -a $HOLY_HERE > /dev/null << END

export HOLY_EAGER=no # git pull blesstheos only by holy update / up
export HOLY_SOURCE=yes # source all of src to make the functions available
export HOLY_EXPORT=yes # export the sourced src helpers to sub-shells too
export HOLY_ALIASES=yes # certain aliases bundled together with abilities
export HOLY_BREW_ON=yes # omit to decrease / skip Homebrew usage

[ -f ~/.bashrc-pre ] && . "\$HOME"/.bashrc-pre

. "\$$HOLY_GOAL"/source.sh
END


touch  ~/.bash_profile
tee -a ~/.bash_profile > /dev/null << END

# source ~/$HOLY_RC
[ -f ~/$HOLY_RC ] && . ~/$HOLY_RC

# code you don't want to run each time .bashrc is sourced
if which rbenv > /dev/null; then eval "\$(rbenv init -)"; fi
END
