#!/usr/bin/env bash

touch  ~/.bash_profile
tee -a ~/.bash_profile > /dev/null << 'END'

# source ~/.bashrc
[ -f ~/.bashrc ] && . ~/.bashrc

# code you don't want to run each time .bashrc is sourced
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
END

touch  ~/.bashrc
tee -a ~/.bashrc > /dev/null << 'END'

export DOT_HOLY=".holy"
export HOLY_BREW_ON=true # omit to decrease / skip Homebrew usage

[ -f ~/.bashrc-pre ] && . "$HOME"/.bashrc-pre
. "$HOME/$DOT_HOLY"/source.sh
END
