#!/usr/bin/env bash

# NOTE: this script should be used through sourcing once.sh

if [ $# -lt 2 ]; then
  echo "This $0 is missing required args:"
  echo "- \$1 HOLY_HOME environment variable name"
  echo "- \$2 path to config file that would export it"
  exit 1
fi

home=$1 # name of the var
this=$2 # a shell's config file that would set the $home environment var
fine=$3 # which means will force it with a warning

lines=$(on-lines "^export ${home}=" $this)
found=$? # $this already exports ${home}? (maybe file not sourced)
if [ $found -eq 0 ]; then
  where="Export of $home found on line: $lines"
fi

if [ -d "${!home}" ]; then
  if [[ "$fine" == "-f" || "$fine" == "--force"  ]]; then
    echo "Forcing an existing install, may have unintended consequences."
    echo "Inspect the following config for similar / identical commands:"
    echo "$this"
    echo "$where"
  else
    echo "Already configured: $this"
    if [ $found -eq 0 ]; then
      echo "$where"
      echo "If \$$home has moved - simply edit the file above."
    else
      echo "Though not finding the export of \$$home in it!"
      echo "If you have edited the file, please open a new shell."
    fi
    exit 1
  fi
elif [ $found -eq 0 ]; then
  echo "It seems you forgot to run: source $this"
  echo "$where"
  # the home dir doesn't exist where it is expected
  # due to being in this branch, and if home is set, so...
  if [ -n "${!home}" ]; then
    # this is a logical interpretation of the issue
    echo "Has your ${!home} been moved by any chance?"
  fi
  exit 1
fi
