#!/usr/bin/env bash

# NOTE: this script should be used through sourcing once.sh

if [ $# -lt 2 ]; then
  echo "This $0 is missing required args:"
  echo "- \$1 HOLY_HOME environment variable name"
  echo "- \$2 path to config file that would export it"
  exit 1
fi

home=$1 # name of the var
this=$2 # a shell's config file that would set the $home environment var
fine=$3 # which means will force it with a warning

match="export ${home}="
found=1 # false for does $this already export $home? (maybe file not sourced)
# NOTE: could just have sourced $this, rather than searching through the file
if grep -q "$match" $this; then
  found=0 # true
  lines=$(grep -n "$match" $this | grep -Eo '^[0-9]*' | awk 'ORS=", "' | head -c -2)
  where="Export of $home found on line: $lines"
  # the reward is reusing this in many places - see the echoes below
fi

if [ -d "${!home}" ]; then
  if [[ "$fine" == "-f" || "$fine" == "--force"  ]]; then
    echo "Forcing an existing install, may have unintended consequences."
    echo "Inspect the following config for similar / identical commands:"
    echo "$this"
    echo "$where"
  else
    echo "Already configured: $this"
    echo "$where"
    echo "If your \$$home has moved - simply edit the file above."
    echo "Can re-init with -f or --force option."
    exit 1
  fi
elif [ $found -eq 0 ]; then
  echo "It seems you forgot to run: source $this"
  echo "$where"
  exit 1
fi
