#!/usr/bin/env bash

# Here I get into the habit of documenting what I install for easier "next time"

# using: onUbuntu; sudoUse; specho
holy-dot src os util

if onUbuntu; then

  sudoUse

  # Flatpak - simply easier to install certain apps with, at least for now...
  sudo apt install -y flatpak gnome-software-plugin-flatpak
  # TODO: look into $XDG_DATA_DIRS
  # /var/lib/flatpak/exports/share
  # ~/.local/share/flatpak/exports/share
  # Because: applications installed by Flatpak may not appear on your desktop -
  # until the session is restarted.

  # Tor Browser
  # https://linuxize.com/post/how-to-install-tor-browser-on-ubuntu-18-04/
  specho Tor Browser ...
  if $(bb -i "(< $(lsb_release -rs) 20.04)"); then
    wget -q -O - https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc | sudo apt-key add -
    echo "deb https://deb.torproject.org/torproject.org $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list
    sudo apt update
    sudo apt install tor deb.torproject.org-keyring torbrowser-launcher
  else
    # Focal "20.04" onward is a simpler install
    sudo apt install torbrowser-launcher
  fi

  if $(bb -i "(>= $(lsb_release -rs) 18.04)"); then
    specho "(GNOME) Tweaks ..."
    sudo apt install gnome-tweak-tool
  fi

  # Etcher
  # https://www.balena.io/etcher/
  # https://github.com/balena-io/etcher#debian-and-ubuntu-based-package-repository-gnulinux-x86x64
  specho Etcher ...
  echo "deb https://deb.etcher.io stable etcher" | sudo tee /etc/apt/sources.list.d/balena-etcher.list
  sudo apt-key adv --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys 379CE192D401AB61
  sudo apt update
  sudo apt install balena-etcher-electron

fi
