#!/usr/bin/env bash

# Decentralization toolset - everything without gui (i.e. cli & backends)

holy-dot src/ install util node os

sudoUse
status=0

if ! silent holy on platform/node; then
  echo "Required holy on platform/node"
  status=1

else
  # NOTE: usually not necessary, though just in case it's a fresh install
  holy-dot use/platform/node

  # https://hypercore-protocol.org/
  specho Hypercore ...
  # https://github.com/hypercore-protocol/cli/
  npm-i -g @hyperspace/cli || noInstall hyp
  # https://github.com/hypercore-protocol/hyperspace/
  npm-i -g hyperspace || noInstall hyperspace

fi

# https://ipfs.io/
specho IPFS ...
if onLinux && snapOn; then
  sudo snap install ipfs
elif onMac && brewOn; then
  brew install ipfs
else
  noInstall ipfs
fi
# ipfs config profile --help
# ipfs init --profile server

exit $status
