#!/usr/bin/env bash

# only for Ubuntu, unless user vouches for it with:
# holy bless platform/docker

# need on servers although also useful for desktops
# run the install/aton first and then this script
# dourbit (urbit) depends on it

holy-dot src/os bin-fn/ silent check-x

# TODO: encapsulate this first if in a function
# this can be reused by all installs for guaranteed idempotency
# and even better, make it a function of holy in...
# for a conditional install with a force option
if silent holy on platform/docker && \
  [[ "$1" != "-f" && "$1" != "--force" ]]; then
  echo "Refusing execution of $0"
  echo "This has already been installed or blessed."
  echo "Run with --force option to install anyway."
elif onUbuntu; then
  # Docker & Docker Compose
  # https://docs.docker.com/install/linux/docker-ce/ubuntu/
  sudo apt remove docker docker-engine docker.io containerd runc
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  sudo apt-key fingerprint 0EBFCD88
  # TODO: verify "9DC8 5822 9FC7 DD38 854A E2D8 8D81 803C 0EBF CD88"
  sudo add-apt-repository \
     "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
     $(lsb_release -cs) \
     stable"
  sudo apt update
  sudo apt install -y docker-ce docker-ce-cli containerd.io docker-compose

  # https://docs.docker.com/install/linux/linux-postinstall/
  sudo groupadd docker
  sudo usermod -aG docker $USER
  newgrp docker
  sudo mkdir -p ~/.docker
  sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
  sudo chmod g+rwx "$HOME/.docker" -R
  sudo systemctl enable docker # start on boot
  sudo systemctl start docker

  # TODO: find the best way to install docker-compose...
  # is pip any better / more recent?
  # https://docs.docker.com/compose/install/

  docker --version
  docker-compose --version
  echo
  echo "try: docker run hello-world #or"
  echo "reboot your system to complete."
else
  # TODO: automate this with a reusable script (holy command?)
  # add it to the other install scripts (code reuse)
  echo "OS not supported for automatic docker install."
  if check-x docker; then # TODO: ? holy confirm platform/docker
    echo "However docker appears to have been installed."
    if ! silent holy on platform/docker; then
      echo "Vouch for this install with: holy bless platform/docker"
    fi
  else
    exit 1
  fi
fi

# TODO: look into not assuming success?
# holy confirm platform/docker # is it meaningful in-between install & reboot?
exit 0
