#!/usr/bin/env bash

# Java 11 (LTS)
# Only for onApt-able (Debian or Ubuntu derivatives, so far...)
# https://adoptopenjdk.net/installation.html?variant=openjdk11&jvmVariant=hotspot#linux-pkg

# Using: onApt
holy-dot src/ os install

if onApt; then

  sudo apt install -y software-properties-common
  wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
  sudo-add-apt-repository https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
  sudo-apt-update
  sudo apt install -y adoptopenjdk-11-hotspot
  java -version

  # only if this is a first-time install
  if ! holy on platform/java > /dev/null && ! tis-some $JAVA_HOME; then
    echo '' >> ~/.bashrc # add an empty line spacer
    echo 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64' >> ~/.bashrc
  fi

else

  echo "You may need to setup java manually, let's see what you have installed:"
  echo $JAVA_HOME
  java -version

fi
