#!/usr/bin/env bash

# install with:
# holy in platform/node && holy-dot use/platform/node

# Node.js via Node Version Manager
# https://github.com/nvm-sh/nvm
# See also:
# `src/nvm.sh` - upgrade of nvm itself + various nvm functions / helpers
# `src/node.sh` - for switching between versions and upgrading / installing
# `use/platform/node` - sourced with holy-dot or holy-f node

# Depends holy on brew (if onMac)
# Install clojure modules (if holy on platform/clojure)
# Using: onLinux onMac specho
holy-dot src/ os node util

# lts/* is the default node, call with "stable" if more recent node is preferred
[[ $# -eq 0 ]] && kind="lts/*" || kind="$1"


# NVM (install)
# NOTE: if not onLinux, have brewOn (HOLY_BREW_ON=yes)
# in order to use brew rather than the install.sh default
if onLinux || ! brewOn; then
  specho "NVM via install.sh"
  echo
  mkdir -p ~/.nvm
  gh-install-xr nvm-sh/nvm install.sh ~/tmp
elif check-x brew; then
  # the above check-x brew is redundant, however enables an easier refactor and
  # kept to prevent future bugs just in case the leading if changes further
  specho "NVM install with brew"
  echo
  mkdir -p ~/.nvm
  brew install nvm
  # next command seems no longer needed and perhaps also destructive (skip)
  # cp $(brew --prefix nvm)/nvm-exec ~/.nvm/
else
  echo "System '${HOLY_KERNEL}' does not meet current requirements."
  exit 1
fi

# Configuration options (the default node version)
echo "$kind" > ~/.nvmrc # nvm use (rather than nvm use default)

# NOTE: immediate nvm use without a new shell session, need to keep it here!
holy-dot use/platform/node

# Some ~/.npmrc options
npm set save-exact true

echo
node-to "$kind" # if node already installed, will reinstall current packages
# Note that the above also makes "lts/*" the default + does `nvm use default`.
status=$?


# TODO: perhaps this belongs to install/npm-local or just install/npm-develop
if onMac; then
  echo "local-npm to be revived only onMac? Not using for now..."
  # TODO: extract to install local-npm via Docker for any development machine
  # NOTE: wait for local-npm 3.0 first
  # https://github.com/local-npm/local-npm
  # https://github.com/local-npm/local-npm/projects/1

  # https://github.com/local-npm/local-npm-launch-agent
  # local / offline partial npm registry cache (only for MacOS)
  # curl -sL https://raw.githubusercontent.com/nolanlawson/local-npm-launch-agent/master/script.py | python -
fi


specho npm install --global packages

# Always have the following packages installed
npm-i -g npm-check npm-check-updates yarn json npm-auto

# Clojure not depending on node, useful though, and usually...
# clojure installed before node, using install/_all or similar
if check-x clojure && silent holy on platform/clojure; then
  npm-i -g node-cljfmt
fi

specho "Default node version of ~/.nvmrc set to $kind"
echo -n "Outcome is a node " && node-v
if [ $# -eq 0 ]; then
  echo "One can change it with this same script, for example:"
  echo -n "holy in platform/node "
  [[ $kind =~ ^lts.* ]] && echo "stable" || echo "lts/*"
  # NOTE: above we give example that's different from the default
  # done with code just in case that changes some day
fi

specho "For immediate use, run:"
echo "holy-dot use/platform/node"

echo
exit $status
