#!/usr/bin/env bash

# install/node && . use/platform/node && nvm use

# Node.js via Node Version Manager
# https://github.com/nvm-sh/nvm
# See also:
# `bin/nvm-up` - upgrade of nvm itself
# `src/node.sh` - for switching between versions and upgrading
# `use/aliases/npm.sh` - useful command aliases

# lts/* is the default node, call with "stable" if more recent node is preferred
[[ $# -eq 0 ]] && kind="lts/*" || kind="$1"

if onLinux; then
  echo "Linux"
  mkdir -p ~/.nvm
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
elif onMac; then
  echo "MacOS"
  mkdir -p ~/.nvm
  cp $(brew --prefix nvm)/nvm-exec ~/.nvm/
else
  echo "System '${HOLY_KERNEL}' is not supported."
  exit 1
fi

# immediate nvm use without a new shell session
holy-dot use platform/node

echo "$kind" > ~/.nvmrc # nvm use rather than nvm use default
node-to "$kind" # if node already installed, will reinstall current packages
# note that the above also makes "lts/*" the default + does `nvm use default`

# TODO: perhaps this belongs to install/npm-local or just install/npm-develop
if onMac; then
  echo "local-npm to be revived..."
  # TODO: extract to install local-npm via Docker for any development machine
  # NOTE: wait for local-npm 3.0 first
  # https://github.com/local-npm/local-npm
  # https://github.com/local-npm/local-npm/projects/1

  # https://github.com/local-npm/local-npm-launch-agent
  # local / offline partial npm registry cache (only for MacOS)
  # curl -sL https://raw.githubusercontent.com/nolanlawson/local-npm-launch-agent/master/script.py | python -
fi

# some npm options write to ~/.npmrc
npm set save-exact true

# always have the following packages installed
npm i -g yarn json
npm i -g npm-check npm-check-updates

# clojure not depending on node, useful though
npm i -g node-cljfmt
