#!/usr/bin/env bash

# only if onApt
holy-dot src/os

if onApt; then

  # python 3 is the only alternative now
  sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 3

  sudo apt install -y python-is-python3 python3-pip python3-markdown python3-tk

  # absolutely need these packages:
  pip3 install pip-review

  python --version #3

else
  exit 1
fi
