#!/usr/bin/env bash

# TODO: make this come from an environment variable $HOLY_RUBY_V,
# as an override, or find some other way to have it not hardcoded
RUBY_V=2.6.3

holy-dot src/ os install

# TODO: perhaps make Homebrew the default if brewOn?
if onMac; then
  echo "Mac OS"
  if brewOn; then
    brew install rbenv ruby-build
  else
    echo "Not On: brew"
    exit 1
  fi

elif onApt; then
  echo "Apt Linux"
  sudo apt install -y rbenv ruby-build

  # dependencies needed for building ruby
  sudo apt install -y libssl-dev libreadline-dev zlib1g-dev

  # to get more ruby versions, down the road:
  # $ cd ~/.rbenv/plugins/ruby-build
  # $ git pull
  # $ rbenv install --list

else
  echo "No ${HOLY_KERNEL} system match!"
  exit 1
fi


# borrowed from https://gist.github.com/brentertz/1384279

if [ ! -f ~/.bundle/config ]; then mkdir -p ~/.bundle && printf -- "---\nBUNDLE_PATH: vendor/bundle\n" >> ~/.bundle/config; fi

if [ ! -f ~/.irbrc ]; then printf "require 'irb/completion'\n" >> ~/.irbrc; fi

if [ ! -f ~/.gemrc ]; then echo "gem: --no-ri --no-rdoc" >> ~/.gemrc; fi

if [ -x rbenv ]; then
  # rbenv install --list
  rbenv install $RUBY_V
  rbenv global $RUBY_V

  gem install bundler --pre
  # TODO: install ../packages/gem
  # rbenv rehash #after installing binaries is automatic / no longer needed

  # per project:
  # rbenv local 1.9.3-p551
  # bundle # installs Gemfile gems to vendor/bundle
fi
