#!/usr/bin/env bash

# borrowed from https://gist.github.com/brentertz/1384279

if onMac; then
  echo "Mac OS"
  brew install rbenv ruby-build

elif onApt; then
  echo "Apt Linux"
  sudo apt install -y rbenv ruby-build

  # dependencies needed for building ruby
  sudo apt install -y libssl-dev libreadline-dev zlib1g-dev

  # to get more ruby versions, down the road:
  # $ cd ~/.rbenv/plugins/ruby-build
  # $ git pull
  # $ rbenv install --list

else
  echo "No ${HOLY_KERNEL} system match!"
fi

if [ ! -f ~/.bundle/config ]; then mkdir -p ~/.bundle && printf -- "---\nBUNDLE_PATH: vendor/bundle\n" >> ~/.bundle/config; fi

if [ ! -f ~/.irbrc ]; then printf "require 'irb/completion'\n" >> ~/.irbrc; fi

if [ ! -f ~/.gemrc ]; then echo "gem: --no-ri --no-rdoc" >> ~/.gemrc; fi

if [ -x rbenv ]; then
  # rbenv install --list
  rbenv install 2.6.3
  rbenv global 2.6.3

  gem install bundler --pre
  # TODO: install ./packages/gem
  # rbenv rehash #after installing binaries is automatic / no longer needed

  # per project:
  # rbenv local 1.9.3-p551
  # bundle # installs Gemfile gems to vendor/bundle
fi
