#!/usr/bin/env bash

# Depends on holy on aton; shell

# Using: sudoUse; onUbuntu; snapOn
holy-dot src/install src os util

status=0

if onUbuntu; then

  sudoUse
  specho "Anbox..."

  if $(bb -i "(< $(lsb_release -rs) 19.04)"); then
    sudo add-apt-repository -y ppa:morphis/anbox-support \
    && sudo apt update -y \
    && sudo apt install -y linux-headers-generic anbox-modules-dkms \
    || noInstall "anbox-support"
  fi

  snapOn && sudo snap install --devmode --beta anbox \
    || noInstall anbox

  sudo apt install -y adb \
    || noInstall adb

else
  noInstall "Anbox just for Ubuntu, please install manually or pull-request."
  echo "https://anbox.io"
fi

# TODO:
# sudo modprobe ashmem_linux
# sudo modprobe binder_linux
# ls -1 /dev/{ashmem,binder}

echo
exit $status
