#!/usr/bin/env bash

# Depends on holy on aton; shell

# Using: sudoUse; onUbuntu; snapOn
holy-dot src/install src os util
status=0

sudoUse
specho "Anbox..."

echo
if onUbuntu; then
  if $(bb -i "(< $(lsb_release -rs) 19.04)"); then
    sudo add-apt-repository -y ppa:morphis/anbox-support \
    && sudo apt update -y \
    && sudo apt install -y linux-headers-generic anbox-modules-dkms \
    || noInstall "anbox-support"
  fi
  # For installing apps from apk files, etc.
  sudo apt install -y \
    android-tools-adb android-tools-fastboot || noInstall "android-tools-*"
else
  echo "Please ensure all the necessary kernel modules are installed."
  echo "https://docs.anbox.io/userguide/install_kernel_modules.html"
fi

echo
snapOn && sudo snap install --devmode --beta anbox || noInstall anbox

specho "Probing for ashmem and binder modules:"
sudo modprobe ashmem_linux
sudo modprobe binder_linux
lsmod | grep -e ashmem_linux -e binder_linux

echo
anbox check-features

echo
exit $status
