#!/usr/bin/env bash

# Ubuntu use so far, or any other apt Linux,
# though nvim would install with brew as an alternative option

for editor in "atom nvim"; do
  if ! holy on "desktop/editor/$editor"; then
    holy in "desktop/editor/$editor"
  fi
done
