#!/usr/bin/env bash

# Ubuntu use so far, or any other apt Linux,
# though nvim would install with brew as an alternative option

editors="atom code nvim"

echo "Editor: $editors"

for editor in $editors; do
  echo
  echo "Install $editor"
  path="desktop/editor/$editor"
  if ! holy on $path; then
    holy in $path
  else
    type $editor
  fi
done
echo
