#!/usr/bin/env bash

# Dependens on: install/aton; install/desktop/packages

# Using: sudoUse; onApt; snapOn; flatpakOn
holy-dot src/ install os install util

status=0
sudoUse

specho "Audio / Music Apps..."
flatpakOn && flatpak install -y flathub org.gnome.Lollypop \
  || noInstall Lollypop

specho "Podcast Apps..."
flatpakOn && flatpak install -y flathub org.gpodder.gpodder \
  || noInstall gPodder

specho "Video Apps..."
# VLC media player
snapOn && sudo snap install vlc \
  || onUbuntu && sudo apt install -y vlc \
  || noInstall VLC
# HandBrake converter
onApt && sudo-add-apt-repository ppa:stebbins/handbrake-releases \
  && sudo-apt-update \
  && sudo apt install -y handbrake-gtk handbrake-cli \
  || noInstall HandBrake

specho "Document - writing and conversion..."
# Writing Editor - various apps available...
# ghostwriter is a very cool app
# TODO: add themes from the following repo?
# https://github.com/jggouvea/ghostwriter-themes
onUbuntu && sudo apt install -y ghostwriter \
  || noInstall ghostwriter
# Mark Text is great but memory-heavy (starts at 1GB thanks to Electron)
flatpakOn && flatpak install -y flathub com.github.marktext.marktext \
  || noInstall "Mark Text"
# Abricotine is neat, but isn't easily update-able on Linux
# https://github.com/brrd/abricotine/blob/master/docs/installation-and-usage.md
#
# Pandoc
brewOn && brew install pandoc \
  && onUbuntu && sudo apt install -y wkhtmltopdf librsvg2-bin \
  || noInstall Pandoc

specho "Ebooks..."
# Foliate Reader
snapOn && sudo snap install foliate \
  || noInstall Foliate
# CHM Reader, not just for Apt...
# https://xchm.sourceforge.io/
onApt && sudo apt install -y xchm \
  || noInstall xCHM
# Calibre Manager (does not update)
# https://calibre-ebook.com/download_linux
onLinux && sudo -v \
  && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin \
  || noInstall Calibre

specho "Convos..."
# https://signal.org
onApt && {
  wget -O- https://updates.signal.org/desktop/apt/keys.asc | sudo apt-key add -
  echo "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main" |\
    sudo tee -a /etc/apt/sources.list.d/signal-xenial.list
  sudo-apt-update
} && sudo apt install -y signal-desktop-beta || noInstall Signal
# https://element.io
onApt && {
  sudo wget -O /usr/share/keyrings/riot-im-archive-keyring.gpg https://packages.riot.im/debian/riot-im-archive-keyring.gpg
  echo "deb [signed-by=/usr/share/keyrings/riot-im-archive-keyring.gpg] https://packages.riot.im/debian/ default main" | sudo tee /etc/apt/sources.list.d/riot-im.list
  sudo-apt-update
} && sudo apt install -y element-desktop || noInstall Element
# https://discord.com
if snapOn; then
  sudo snap install discord
  sudo snap connect discord:system-observe
elif flatpakOn; then
  flatpak install -y flathub com.discordapp.Discord
else
  noInstall Discord
fi

specho "Conference..."
onApt && cd /tmp && wget https://zoom.us/client/latest/zoom_amd64.deb \
  && sudo apt install -y ./zoom_amd64.deb \
  && rm ./zoom_amd64.deb && cd - \
  || noInstall Zoom

specho "Compression..."
onApt && sudo apt install -y unrar rar \
  || noInstall "*rar"
# unpack messages in MIME or split-uuencode format
onApt && sudo apt install -y mpack \
  || noInstall "mpack" # munpack *.eml

specho "Images..."
# https://github.com/muennich/sxiv
onApt && sudo apt install -y sxiv \
  || noInstall sxiv
# https://flameshot.org/
snapOn && sudo snap install flameshot \
  || noInstall flameshot

echo
exit $status
