#!/usr/bin/env bash

# Depends on aton
# Using: check-x; onApt; sudoUse
holy-dot bin-fn/check-x src/ os install util

if onApt; then
  sudoUse
  check-x atom && echo "Notice: atom is already installed" && type atom
  wget -qO - https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -
  sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'
  sudo-apt-update
  sudo apt install -y atom
else
  exit 1
fi

type atom
