#!/usr/bin/env bash

holy-dot src/os

if onApt; then
  check-x atom && echo "notice atom is already installed" && type atom
  wget -qO - https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -
  sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'
  sudo apt update
  sudo apt install -y atom
else
  exit 1
fi

type atom
