#!/usr/bin/env bash

# Depends on aton
# Using: check-x; onApt; sudoUse
holy-dot bin-fn/check-x src/ os util

if onApt; then
  sudoUse
  check-x code && echo "Notice: code, i.e. VSCode, is already installed" && type code
  wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
  sudo add-apt-repository -y "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
  sudo-apt-update
  sudo apt install -y code
else
  exit 1
fi

type code
