#!/usr/bin/env bash

holy-dot src os util

if onApt; then
  check-x nvim && echo "Notice: nvim is already installed" && type nvim
  sudo apt install -y neovim
elif brewOn; then
  # notice how apt is preferable
  brew install neovim
else
  exit 1
fi

type nvim
