#!/usr/bin/env bash

# Using: onApt sudoUse noInstall
holy-dot src/ install os util
status=0

check-x nvim && echo "Notice: nvim is already installed, proceeding anyway"

if onApt; then
  sudoUse
  sudo apt install -y neovim || noInstall "nvim via apt"
elif check-x brew; then
  # apt is preferable as possible and brewOn irrelevant
  brew install neovim
else
  noInstall "nvim"
fi

tis-true $status && type nvim

exit $status
