#!/usr/bin/env bash

# Using: sudoUse
holy-dot src/util

sudoUse

# needed for many of the install scripts; find the MacOS equivalents...
holy in aton

# Homebrew usage depends on `export HOLY_BREW_ON=true`; MacOS may need update
holy in brew

# scripting with bash and sometimes also bb
holy in shell

# unless onApt -- manually download and install AdoptOpenJDK
# https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot
holy in platform/java

# depends on shell & java
holy in closh

# depends on `java`, with `brewOn` for some of the installs
holy in platform/clojure

# MacOS version has worked in the past, though not tested lately...
holy in platform/node && holy-dot use/platform/node

# decentralized tools
holy in platform/decent && holy-dot use/platform/decent

# via `brew` on a Mac - maybe unify for all to be brew-based...
holy in platform/ruby && holy-dot use/platform/ruby

# only apt, though that will eventually change
holy in platform/python && holy-dot use/platform/python

# it's just for Linux, just about fully...
holy in term

# if not `onUbuntu` then may have to re-install some of these later
holy in desktop/_os/ubuntu
holy in desktop/packages
holy in desktop/editors
holy in desktop/media
holy in desktop/anbox

# and certain `docker` containers if wanted (after reboot)
holy in platform/docker

# Note may need a reboot before using urbit
# and also for running the docker container installs
holy in urbit
