#!/usr/bin/env bash

sudoUse
cd "$DOTS_HOME"/install

./atops   # needed for many of the install scripts; find the MacOS equivalents...
./brew    # Homebrew usage depends on `export BREW_ON=true`; MacOS may need update
./shell   # scripting with `bash` + `bb` or `closh`; `which bb` depends on `brewOn`
./java    # unless Ubuntu / Debian: manually download and install AdoptOpenJDK
          # https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot
./clojure # depends on `java`, with `brewOn` for some of the installs
./node && uses platforms/node.sh && nvm use
          # MacOS version has worked in the past, though not tested lately...
./ruby    # via `brew` on a Mac - maybe unify for all to be brew-based...
./term    # it's just for Linux, almost fully...
./editor  # if not `onApt` (e.g. Ubuntu) then would have to install Atom by hand
./python  # only apt, though that will eventually change
./ubuntu-docker # and certain `docker` containers
./ubuntu-desktop
