#!/usr/bin/env bash

# only for Debian / Ubuntu so far...
# what is generally needed by a system (for other installs)

if onApt; then

  echo "Apt Linux"
  sudo apt update
  sudo apt install build-essential git file
  sudo apt install apt-transport-https curl wget
  sudo apt install \
        ca-certificates \
        gnupg-agent \
        software-properties-common

elif onMac; then
  echo "MacOS - TODO..."
else
  echo "No ${KERNEL_NAME} system match!"
fi
