#!/usr/bin/env bash

source "$DOTS_HOME/use/helpers/os.sh"

# only for Debian / Ubuntu

if onApt; then

  sudo apt install python-pip python-markdown python-tk

  # prefer python 3
  sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 2
  sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 3

  sudo apt install python3-pip python3-markdown python3-tk

  # https://github.com/Coldcard/ckcc-protocol - see requirements / install:
  sudo apt install python3-hidapi python3-ecdsa python3-pyaes python3-click
  # https://github.com/signal11/hidapi/tree/master/linux
  sudo apt install libhidapi-dev libusb-1.0-0-dev libudev-dev
  # ckcc # Coldcard cli tool:
  pip install 'ckcc-protocol[cli]'
  ln -s ~/.local/bin/ckcc ~/.bin/

  python --version #3

fi
