#!/usr/bin/env bash

# only for Debian / Ubuntu
# here I get into the habit of documenting what I install for easier "next time"

if onApt; then

  sudoUse

  # Tor Browser
  # https://linuxize.com/post/how-to-install-tor-browser-on-ubuntu-18-04/
  if onUbuntu; then
    specho Tor Browser ...
    if $(bb -i "(< $(lsb_release -rs) 20.04)"); then
      wget -q -O - https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc | sudo apt-key add -
      echo "deb https://deb.torproject.org/torproject.org $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list
      sudo apt update
      sudo apt install tor deb.torproject.org-keyring torbrowser-launcher
    else
      # Focal "20.04" onward is a simpler install
      sudo apt install torbrowser-launcher
    fi
  fi

  # Etcher
  # https://www.balena.io/etcher/
  # https://github.com/balena-io/etcher#debian-and-ubuntu-based-package-repository-gnulinux-x86x64
  specho Etcher ...
  echo "deb https://deb.etcher.io stable etcher" | sudo tee /etc/apt/sources.list.d/balena-etcher.list
  sudo apt-key adv --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys 379CE192D401AB61
  sudo apt update
  sudo apt install balena-etcher-electron

fi

if onApt && false; then
  # Things I plan to stop using.

  # Keybase
  # https://keybase.io/docs/the_app/install_linux
  specho Keybase ...
  curl --remote-name https://prerelease.keybase.io/keybase_amd64.deb
  sudo apt install ./keybase_amd64.deb
  rm ./keybase_amd64.deb
  run_keybase

fi
