#!/usr/bin/env bash

status=0
holy-dot src/ os install

# only for Debian / Ubuntu so far...
# what is generally needed by a system (for other installs)

if onApt; then
  echo "Apt Linux"
  sudo-apt-update
  sudo apt install -y build-essential git file git-lfs
  git lfs install --force
  if [ ! -f ~/.gitconfig ]; then cp "$HOLY_HOME"/home/.gitconfig ~/; fi
  sudo apt install -y apt-transport-https curl wget
  sudo apt install -y \
        ca-certificates \
        gnupg-agent \
        software-properties-common \
        ppa-purge
  sudo apt install -y gawk # needed for JSONPath.sh
else
  >&2 echo "No ${HOLY_KERNEL} system match!"
  status=1
fi

if [ $status -eq 0 ]; then
  mkdir -p ~/tmp
  touch ~/.bashrc-pre
fi

exit $status
