#!/usr/bin/env bash

mkdir -p ~/tmp
touch ~/.bashrc-pre

# only for Debian / Ubuntu so far...
# what is generally needed by a system (for other installs)

if onApt; then

  echo "Apt Linux"
  sudo apt update
  sudo apt install -y build-essential git file git-lfs
  git lfs install --force
  if [ ! -f ~/.gitconfig ]; then cp "$HOLY_HOME"/home/.gitconfig ~/; fi
  sudo apt install -y apt-transport-https curl wget
  sudo apt install \
        ca-certificates \
        gnupg-agent \
        software-properties-common
  sudo apt install -y gawk # needed for JSONPath.sh

elif onMac; then
  echo "MacOS - TODO..."
else
  echo "No ${KERNEL_NAME} system match!"
fi
