#!/usr/bin/env bash

# what is generally needed by a system / for other installs

source "$DOTS_HOME/use/helpers/os.sh"

if onLinux; then
  echo "Linux"
  # only for Debian / Ubuntu

  sudo apt update
  sudo apt install build-essential git file
  sudo apt install apt-transport-https curl wget
  sudo apt install \
        ca-certificates \
        gnupg-agent \
        software-properties-common

elif onMac; then
  echo "MacOS - TODO..."
else
  echo "No ${system_name} system match!"
fi
