#!/usr/bin/env bash

# https://brew.sh/
# https://docs.brew.sh/Installation
# https://docs.brew.sh/Homebrew-on-Linux

if onMac; then
  echo "MacOS has not been tested yet.  Will not install."
  exit 0
fi

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

# NOTE: the following 2 lines are Linux-specific...  Where does it go on a Mac?
test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

echo "" >>~/.profile
echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile

echo "" >>~/.bashrc-pre
echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bashrc-pre

# if you install something by mistake then `brew rmtree package`
# https://stackoverflow.com/questions/7323261/uninstall-remove-a-homebrew-package-including-all-its-dependencies
brew tap beeftornado/rmtree

# Eventually these will get split in 3 files: linux-only, mac-only, and shared.
# Here is a fresh start for what should end up as shared. None are necessary...
if brewOn; then
  if ! onApt; then brew install transmission-cli; fi # apt is preferable
fi
