#!/usr/bin/env bash

# https://brew.sh/
# https://docs.brew.sh/Installation
# https://docs.brew.sh/Homebrew-on-Linux

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

echo "" >>~/.profile
echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile

# log out for `brew` to work, meanwhile install gcc (as recommended)
eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
brew install gcc
