#!/usr/bin/env bash

# https://brew.sh/
# https://docs.brew.sh/Installation
# https://docs.brew.sh/Homebrew-on-Linux

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

echo "" >>~/.profile
echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile

# log out for `brew` to work, meanwhile install gcc (as recommended)
eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

# if you install something by mistake then `brew rmtree package`
# https://stackoverflow.com/questions/7323261/uninstall-remove-a-homebrew-package-including-all-its-dependencies
brew tap beeftornado/rmtree

# Eventually these will get split in 3 files: linux-only, mac-only, and shared.
# Here is a fresh start for what should end up as shared.
brew install gcc #suggested
brew install neovim #run as nvim
