#!/usr/bin/env bash

# Based on https://purelyfunctional.tv/guide/how-to-install-clojure/

# Expected deps
echo $JAVA_HOME
java -version
brew --version

# Leiningen
curl https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein > lein
sudo mv lein /usr/local/bin/lein
sudo chmod a+x /usr/local/bin/lein
lein version

# Clojure
brew update
brew install clojure/tools/clojure
clj -e '(println (str "Clojure " (clojure-version)))'
