#!/usr/bin/env bash

# Based on https://purelyfunctional.tv/guide/how-to-install-clojure/

# Expected deps
echo $JAVA_HOME
java -version
brew --version

# Leiningen
curl https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein > lein
sudo mv lein /usr/local/bin/lein
sudo chmod a+x /usr/local/bin/lein
LPROF=".lein/profiles.clj"
# NOTE: would be nice to merge the profiles rather than the simple off / on
[[ -f "$HOME/$LPROF" ]] || cp -r ${DOTS_HOME}/files/${LPROF} ~/${LPROF}
lein version

# Clojure
brew update
brew install clojure/tools/clojure
clj -e '(println (str "Clojure " (clojure-version)))'

# Clj-kondo
# https://github.com/borkdude/clj-kondo
brew install borkdude/brew/clj-kondo
clj-kondo --version
