#!/usr/bin/env bash

# Primarily Ubuntu use so far...

if onApt; then
  sudo apt install neovim # nvim
  # Atom:
  wget -qO - https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -
  sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'
  sudo apt update
  sudo apt install atom
elif brewOn; then
  # notice how apt is preferable
  brew install neovim # nvim
fi
