#!/usr/bin/env bash

# only for Debian / Ubuntu
# here I get into the habit of documenting what I install for easier "next time"

# https://keybase.io/docs/the_app/install_linux
curl --remote-name https://prerelease.keybase.io/keybase_amd64.deb
sudo apt install ./keybase_amd64.deb
rm ./keybase_amd64.deb
run_keybase
