#!/usr/bin/env bash

# only for Debian / Ubuntu
# here I get into the habit of documenting what I install for easier "next time"

# Tor Browser
# https://linuxize.com/post/how-to-install-tor-browser-on-ubuntu-18-04/
wget -q -O - https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc | sudo apt-key add -
echo "deb https://deb.torproject.org/torproject.org $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list
sudo apt update
sudo apt install tor deb.torproject.org-keyring torbrowser-launcher

# Keybase
# https://keybase.io/docs/the_app/install_linux
curl --remote-name https://prerelease.keybase.io/keybase_amd64.deb
sudo apt install ./keybase_amd64.deb
rm ./keybase_amd64.deb
run_keybase
