#!/usr/bin/env bash

# Node.js via Node Version Manager
# https://github.com/nvm-sh/nvm
# See also:
# `../bin/nvm-up` - upgrade nvm
# `../bin/node-up` - node lts default, with latest npm, and same global packages
# `../aliases/npm.sh` - useful command aliases

system_name=`uname -s`

if [ "$system_name" == 'Darwin' ]; then
  echo "MacOS"
  mkdir ~/.nvm
  cp $(brew --prefix nvm)/nvm-exec ~/.nvm/
elif [ "$system_name" == 'Linux' ]; then
  echo "Linux"
  mkdir ~/.nvm
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
else
  echo "System '${system_name}' is not supported."
  exit 1
fi

# immediate nvm use without a new shell session
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

echo "stable" > ~/.nvmrc # tho the alias below overrides this...
nvm install lts/*
nvm alias default lts/*
exec $SHELL

if [ "$system_name" == 'Darwin' ]; then
  # local / offline partial npm registry cache (only for MacOS)
  curl -sL https://raw.githubusercontent.com/nolanlawson/local-npm-launch-agent/master/script.py | python -
fi

# some npm options (reminders)
npm set save-exact true
npm install -g yarn
npm install -g npm-check
npm install -g npm-check-updates
