#!/usr/bin/env bash

mkdir ~/.nvm

if [ $system_name == 'Darwin' ]; then
  cp $(brew --prefix nvm)/nvm-exec ~/.nvm/
fi

echo "stable" > ~/.nvmrc # tho the alias below overrides this...
nvm alias default stable # to begin with (lts or specific may be preferable)

# some npm options (reminders)
npm set save-exact true
