#!/usr/bin/env bash

# borrowed from https://gist.github.com/brentertz/1384279

if [ $system_name == 'Darwin' ]; then
  brew install rbenv
  brew install ruby-build
fi

if [ ! -f ~/.bundle/config ]; then mkdir -p ~/.bundle && printf -- "---\nBUNDLE_PATH: vendor/bundle\n" >> ~/.bundle/config; fi

if [ ! -f ~/.irbrc ]; then printf "require 'irb/completion'\n" >> ~/.irbrc; fi

rbenv install 1.9.3-p551
rbenv rehash #after installing binaries
rbenv global 1.9.3-p551

sudo gem install bundler --pre
sudo gem install compass ghost # ronn
rbenv rehash

# per project:
# rbenv local 1.9.3-p551
# bundle # installs Gemfile gems to vendor/bundle
