#!/usr/bin/env bash

system_name=`uname -s`

if [ "$system_name" == 'Darwin' ]; then
  echo "MacOS"

  # the following will add a line to .profile or .bash_profile / something
  curl -L https://iterm2.com/misc/install_shell_integration.sh | bash

else
  echo "No ${system_name} system match!"
fi
