#!/usr/bin/env bash

sudoUse

# https://github.com/borkdude/babashka
specho Babashka ...
if brewOn; then
  brew install borkdude/brew/babashka
else
  sudomy gh-install-xr borkdude/babashka install ~/tmp
fi

# http://www.bpkg.sh/
# NOTE: using this is kind of funky
# there is no use for bpkg at the moment
# curl -sLo- http://get.bpkg.sh | bash

# NOTE some issues with bpkg:
# * global install with sudo doesn't work as bpkg is installed locally
# * local installs stick a deps/ in a current dir
# * package.json is a poor choice, as it overlaps with npm's package.json
# people are in fact using npm to deploy shell scripts
# npm is ok, except I rather run certain scripts without any install deps

# Installing from the source instead - see next block...
# The package below just a fork; plus it renames JSON.sh to JSON (I rather not)
# http://www.bpkg.sh/pkg/jsonsh
# cd ~
# bpkg install json.sh
# cd -
# source ~/.bashrc # ~/deps/bin dir just got created, this should add it to $PATH

# https://github.com/dominictarr/JSON.sh
specho JSON.sh ...
gh-install dominictarr/JSON.sh JSON.sh ~/bin

# https://github.com/mclarkson/JSONPath.sh
# https://cburgmer.github.io/json-path-comparison/
specho JSONPath.sh ...
gh-install mclarkson/JSONPath.sh JSONPath.sh ~/bin

# https://github.com/cute/JSONPretty
specho JSONPretty.sh ...
gh-install cute/JSONPretty JSONPretty.sh ~/bin

# https://github.com/dundalek/closh
specho Closh ...
$(dirname $0)/closh # install here, because it's a shell
