#!/usr/bin/env bash

# Various terminal themes and tools

# changes theme on both Linux and MacOS iTerm:
# bash -c  "$(wget -qO- https://git.io/vQgMr)"
# though prefer xfce on Linux (skip for that)

sudoUse

if check-x gsettings; then
  # For Gnome, this will make the terminal window frame flash for a visual bell
  gsettings set org.gnome.desktop.wm.preferences audible-bell false
  gsettings set org.gnome.desktop.wm.preferences visual-bell true
  gsettings set org.gnome.desktop.wm.preferences visual-bell-type frame-flash
fi

if onLinux; then
  # URxvt & XTerm
  if [ ! -f ~/.Xresources ]; then
    cp "$DOTS_HOME"/home/.Xresources ~
  else
    echo ".Xresouces already exists, thus skipping use of:"
    echo "$DOTS_HOME"/home/.Xresources
  fi
  cd ~; ln -s .Xresources .Xdefaults-$(hostname) # this could be just for Ubuntu
  # Xfce4 Terminal Themes
  onApt && sudo apt -y install xfce4-terminal
  mkdir -p ~/.local/share/xfce4/terminal/colorschemes
  cp "$DOTS_HOME"/files/themes/xfce4/* ~/.local/share/xfce4/terminal/colorschemes
  if [ ! -f  ~/.config/xfce4/terminal/terminalrc ]; then
    mkdir -p ~/.config/xfce4/terminal
    cp "$DOTS_HOME"/files/xfce4/terminalrc ~/.config/xfce4/terminal/terminalrc
  fi
  # Fonts
  $destination="/usr/share/fonts/truetype/iosevka-custom"
  # Building my own Custom Iosevka here:
  gh-install orlin/Iosevka dist/iosevka-custom/ttf.zip ~/tmp build
  cd ~/tmp && rm -rf ttf && unzip ttf.zip
  sudo rm -rf $destination
  sudo mkdir -p $destination
  sudo mv ~/tmp/ttf/*.ttf $destination
  fc-cache -f
  rm -rf ~/tmp/ttf*
fi

if onApt; then
  # fonts:
  sudo apt -y install fonts-firacode fonts-inconsolata fonts-hack-ttf
  # themes:
  sudo apt -y install dconf-cli uuid-runtime
  # tools:
  sudo apt install -y tmux
  sudo apt install -y ncdu # http://dev.yorhel.nl/ncdu NCurses Disk Usage
  # https://askubuntu.com/questions/257263/how-to-display-network-traffic-in-the-terminal
  sudo apt install -y htop glances # monitor system processes and much more
  sudo apt install -y bmon slurm tcptrack iftop nethogs # network interface(s)
  sudo apt install -y speedometer # graph network traffic with custom chart max
  # speedometer -l  -t eth0 -r eth0 -m $(( 1024 * 1024 * 9 ))
elif onMac; then
  brewOn && brew tap homebrew/cask-fonts && brew cask install font-iosevka && brew cask install font-iosevka-slab
  specho iTerm2 Shell Integrations ...
  # the following will add a line to .profile or .bash_profile / something
  curl -L https://iterm2.com/misc/install_shell_integration.sh | bash
fi
