#!/usr/bin/env bash

# only for Ubuntu
# need on servers although also useful for desktops
# run the install/atop first and then this script

if onUbuntu; then

  # Docker & Docker Compose
  # https://docs.docker.com/install/linux/docker-ce/ubuntu/
  sudo apt remove docker docker-engine docker.io containerd runc
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  sudo apt-key fingerprint 0EBFCD88
  # TODO: verify "9DC8 5822 9FC7 DD38 854A E2D8 8D81 803C 0EBF CD88"
  sudo add-apt-repository \
     "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
     $(lsb_release -cs) \
     stable"
  sudo apt update
  sudo apt install -y docker-ce docker-ce-cli containerd.io

  # https://docs.docker.com/install/linux/linux-postinstall/
  sudo groupadd docker
  sudo usermod -aG docker $USER
  newgrp docker
  sudo mkdir -p ~/.docker
  sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
  sudo chmod g+rwx "$HOME/.docker" -R
  docker run hello-world
  sudo systemctl start docker
  sudo systemctl enable docker # start on boot

  # https://docs.docker.com/compose/install/
  sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  sudo chmod +x /usr/local/bin/docker-compose
  docker --version
  docker-compose --version

fi
