#!/usr/bin/env bash

if ! check-x docker; then
  onUbuntu && echo "Please first run ${DOTS_HOME}/install/ubuntu-docker" \
           || echo "Please first install docker"
  exit 0
fi

mkdir -p ~/data/urbit # for all ships' data - planets, comets and so on...
mkdir -p ~/bin/urbit-os # not in the $PATH so will only run via the urbit-os script

specho Download some urbit-os commands:
echo

gh-install orlin/urbit-docker scripts/createcomet.sh \
          ~/tmp master ~/bin/urbit-os/new-comet \
          && echo

gh-install orlin/urbit-docker scripts/createship.sh \
          ~/tmp master ~/bin/urbit-os/new-ship \
          && echo

gh-install orlin/urbit-docker scripts/run \
          ~/tmp master ~/bin/urbit-os/run \
          && echo
