#!/usr/bin/env bash

if ! check-x docker; then
  onUbuntu && echo "Please first run ${DOTS_HOME}/install/ubuntu-docker" \
           || echo "Please first install docker"
  exit 0
fi

mkdir -p ~/data/urbit # for all ships' data - planets, comets and so on...
mkdir -p ~/bin/dourbit # not in $PATH - run these scripts as dourbit commands

specho Download some urbit commands:
echo

gh-install orlin/urbit-docker scripts/createcomet.sh \
          ~/bin/dourbit master new-comet \
          && echo

gh-install orlin/urbit-docker scripts/createship.sh \
          ~/bin/dourbit master new-ship \
          && echo

gh-install orlin/urbit-docker scripts/run \
          ~/bin/dourbit \
          && echo

if [[ ! -e "${DOTS_HOME}/use/repos/urbit" ]]; then
  git clone --depth 1 --single-branch --branch master \
      https://github.com/urbit/urbit.git \
      ${DOTS_HOME}/use/repos/urbit
else
  echo "Exists: ${DOTS_HOME}/use/repos/urbit"
fi
echo

if [[ ! -e "${DOTS_HOME}/use/repos/urbit-docker" ]]; then
  git clone https://github.com/orlin/urbit-docker.git \
      ${DOTS_HOME}/use/repos/urbit-docker
else
  echo "Exists: ${DOTS_HOME}/use/repos/urbit-docker"
fi
echo
