#!/usr/bin/env bash

if ! check-x docker; then
  onUbuntu && echo "Please first run ${DOTS_HOME}/install/ubuntu-docker" \
           || echo "Please first install docker"
  exit 0
fi

mkdir -p ~/data/urbit # for all ships' data - planets, comets and so on...
mkdir -p ~/bin/urbit-os # not in the $PATH so will only run via the urbit-os script

specho Install commands ...

specho urbit-os new-comet ...
gh-install orlin/urbit-docker scripts/createcomet.sh ~/tmp && \
  mv ~/tmp/createcomet.sh ~/bin/urbit-os/new-comet && \
  echo Renamed: ~/bin/urbit-os/new-comet

specho urbit-os new-ship ...
gh-install orlin/urbit-docker scripts/createship.sh ~/tmp && \
  mv ~/tmp/createship.sh ~/bin/urbit-os/new-ship && \
  echo Renamed: ~/bin/urbit-os/new-ship

specho urbit-os run ...
gh-install orlin/urbit-docker scripts/run ~/tmp && \
  mv ~/tmp/run ~/bin/urbit-os/run && \
  echo Renamed: ~/bin/urbit-os/run
