#!/usr/bin/env bash

# https://www.bitcoindockers.com/
# https://github.com/SatoshiPortal/dockers/tree/master/bitcoin-core

sudo useradd bitcoinuser
mkdir -m 2770 -p ~/data/btc
sudo chown -R bitcoinuser:`id -gn` ~/btcdata
sudo find ~/btcdata -type f -exec chmod g+rw {} \; ; sudo find ~/btcdata -type d -exec chmod g+rwx {} \;

cd /tmp
git clone https://github.com/SatoshiPortal/dockers.git
cd dockers/bitcoin-core/
docker build -t btcnode --build-arg ARCH=x86_64 .
cd /tmp && rm -rf dockers

docker run -d --restart always --name btcnode \
  -p 18333:18333 -p 18332:18332 -p 29000:29000 \
  -v ~/data/btc:/.bitcoin \
  btcnode `id -u bitcoinuser`:`id -g bitcoinuser` bitcoind

# TODO: add manual step of changing ~/data/btc/bitcoin.conf (or automate how?)
# NOTE: it's configured for testnet by default
