#!/usr/bin/env bash

# https://www.bitcoindockers.com/
# https://github.com/SatoshiPortal/dockers/tree/master/bitcoin-core

sudo useradd bitcoinuser
mkdir -m 2770 -p ~/data/btc
sudo chown -R bitcoinuser:`id -gn` ~/data/btc
sudo find ~/data/btc -type f -exec chmod g+rw {} \;
sudo find ~/data/btc -type d -exec chmod g+rwx {} \;
sudo usermod -aG bitcoinuser $USER
ln -s ~/data/btc/ ~/.bitcoin

cd /tmp
git clone https://github.com/SatoshiPortal/dockers.git
cd dockers/bitcoin-core/
docker build -t btcnode --build-arg ARCH=x86_64 .
cd /tmp && rm -rf dockers

docker run --detach --restart always --name btcnode \
  -p 8333:8333 -p 8332:8332 -p 29000:29000 \
  -v ~/data/btc:/.bitcoin \
  btcnode `id -u bitcoinuser`:`id -g bitcoinuser` bitcoind

# TODO: add manual step of changing ~/data/btc/bitcoin.conf (or automate how?)
# NOTE: it's configured for testnet by default

# https://github.com/Samourai-Wallet/samourai-dojo
# https://github.com/Samourai-Wallet/samourai-dojo/blob/develop/doc/DOCKER_advanced_setups.md
